CREATE DATABASE IF NOT EXISTS product_management;
USE product_management;
CREATE TABLE SĐT (
    SĐT_NHACC VARCHAR(12) PRIMARY KEY
);

CREATE TABLE NHACC (
    MANCC VARCHAR(6) PRIMARY KEY,
    TenNCC VARCHAR(50),
    DiaChi VARCHAR(50),
    SĐT_NHACC VARCHAR(12),
    FOREIGN KEY (SĐT_NHACC)
        REFERENCES SĐT (SĐT_NHACC)
);

CREATE TABLE DONDH (
    SoDH INT PRIMARY KEY,
    NgayDH DATE,
    MANCC VARCHAR(6),
    FOREIGN KEY (MANCC)
        REFERENCES NHACC (MANCC)
);

CREATE TABLE VATTU (
    MAVTU VARCHAR(10) PRIMARY KEY,
    TenVTU VARCHAR(50)
);

CREATE TABLE CHI_TIET_DON_DAT_HANG (
    SoDH INT,
    MAVTU VARCHAR(10),
    PRIMARY KEY (SoDH , MAVTU),
    FOREIGN KEY (SoDH)
        REFERENCES DONDH (SoDH),
    FOREIGN KEY (MAVTU)
        REFERENCES VATTU (MAVTU)
);

CREATE TABLE PHIEUXUAT (
    SoPX INT PRIMARY KEY,
    NgayXuat DATE
);

CREATE TABLE CHI_TIET_PHIEU_XUAT (
    SoPX INT,
    MAVTU VARCHAR(10),
    DGXuat VARCHAR(100),
    SLXuat VARCHAR(100),
    PRIMARY KEY (SoPX , MAVTU),
    FOREIGN KEY (SoPX)
        REFERENCES PHIEUXUAT (SoPX),
    FOREIGN KEY (MAVTU)
        REFERENCES VATTU (MAVTU)
);

CREATE TABLE PHIEUNHAP (
    SoPN INT PRIMARY KEY,
    NgayNhap DATE
);

CREATE TABLE CHI_TIET_PHIEU_NHAP (
    SoPN INT,
    MAVTU VARCHAR(10),
    DGNhap VARCHAR(100),
    SLNhap VARCHAR(100),
    PRIMARY KEY (SoPN , MAVTU),
    FOREIGN KEY (SoPN)
        REFERENCES PHIEUNHAP (SoPN),
    FOREIGN KEY (MAVTU)
        REFERENCES VATTU (MAVTU)
);