CREATE DATABASE IF NOT EXISTS product_management;
USE product_management;
CREATE TABLE SĐT (
    SĐT_NHACC VARCHAR(12) PRIMARY KEY
);

CREATE TABLE NHACC (
    MA_NCC VARCHAR(6) PRIMARY KEY,
    Ten_NCC VARCHAR(50),
    Dia_Chi VARCHAR(50),
    SĐT_NHACC VARCHAR(12),
    FOREIGN KEY (SĐT_NHACC)
        REFERENCES SĐT (SĐT_NHACC)
);

CREATE TABLE DON_DH (
    So_DH INT PRIMARY KEY,
    Ngay_DH DATE,
    MA_NCC VARCHAR(6),
    FOREIGN KEY (MA_NCC)
        REFERENCES NHACC (MA_NCC)
);

CREATE TABLE VAT_TU (
    MA_VTU VARCHAR(10) PRIMARY KEY,
    Ten_VTU VARCHAR(50)
);

CREATE TABLE CHI_TIET_DON_DAT_HANG (
    So_DH INT,
    MA_VTU VARCHAR(10),
    PRIMARY KEY (So_DH , MA_VTU),
    FOREIGN KEY (So_DH)
        REFERENCES DON_DH (So_DH),
    FOREIGN KEY (MA_VTU)
        REFERENCES VAT_TU (MA_VTU)
);

CREATE TABLE PHIEU_XUAT (
    So_PX INT PRIMARY KEY,
    Ngay_Xuat DATE
);

CREATE TABLE CHI_TIET_PHIEU_XUAT (
    So_PX INT,
    MA_VTU VARCHAR(10),
    DG_Xuat VARCHAR(100),
    SL_Xuat VARCHAR(100),
    PRIMARY KEY (So_PX , MA_VTU),
    FOREIGN KEY (So_PX)
        REFERENCES PHIEU_XUAT (So_PX),
    FOREIGN KEY (MA_VTU)
        REFERENCES VAT_TU (MA_VTU)
);

CREATE TABLE PHIEU_NHAP (
    So_PN INT PRIMARY KEY,
    Ngay_Nhap DATE
);

CREATE TABLE CHI_TIET_PHIEU_NHAP (
    So_PN INT,
    MA_VTU VARCHAR(10),
    DG_Nhap VARCHAR(100),
    SL_Nhap VARCHAR(100),
    PRIMARY KEY (So_PN , MA_VTU),
    FOREIGN KEY (So_PN)
        REFERENCES PHIEU_NHAP (So_PN),
    FOREIGN KEY (MA_VTU)
        REFERENCES VAT_TU (MA_VTU)
);